export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const USER_STATUS_REQUEST = 'USER_STATUS_REQUEST';
export const USER_STATUS_SUCCESS = 'USER_STATUS_SUCCESS';
export const USER_STATUS_FAILURE = 'USER_STATUS_FAILURE';

export const USER_ROLE_REQUEST = 'USER_ROLE_REQUEST';
export const USER_ROLE_SUCCESS = 'USER_ROLE_SUCCESS';
export const USER_ROLE_FAILURE = 'USER_ROLE_FAILURE';

export const USER_LOAD_DATA_REQUEST = 'USER_LOAD_DATA_REQUEST';
export const USER_LOAD_DATA_SUCCESS = 'USER_LOAD_DATA_SUCCESS';
export const USER_LOAD_DATA_FAILURE = 'USER_LOAD_DATA_FAILURE';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
export const RESET_USER_STATUS = 'RESET_USER_STATUS';
export const RESET_GROUP_STATUS = 'RESET_GROUP_STATUS';
export const RESET_DEVICE_STATUS = 'RESET_DEVICE_STATUS';
export const GROUP_CONNECTED_STATUS = 'GROUP_CONNECTED_STATUS';


export const GROUP_CREATE_REQUEST = 'GROUP_CREATE_REQUEST';
export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS';
export const GROUP_CREATE_FAILURE = 'GROUP_CREATE_FAILURE';

export const GROUP_JOIN_REQUEST = 'GROUP_JOIN_REQUEST';
export const GROUP_JOIN_SUCCESS = 'GROUP_JOIN_SUCCESS';
export const GROUP_JOIN_FAILURE = 'GROUP_JOIN_FAILURE';

export const GROUP_LOAD_JOIN_REQUEST = 'GROUP_LOAD_JOIN_REQUEST';
export const GROUP_LOAD_JOIN_SUCCESS = 'GROUP_LOAD_JOIN_SUCCESS';
export const GROUP_LOAD_JOIN_FAILURE = 'GROUP_LOAD_JOIN_FAILURE';

export const GROUP_LOAD_MEMBERS_REQUEST = 'GROUP_LOAD_MEMBERS_REQUEST';
export const GROUP_LOAD_MEMBERS_SUCCESS = 'GROUP_LOAD_MEMBERS_SUCCESS';
export const GROUP_LOAD_MEMBERS_FAILURE = 'GROUP_LOAD_MEMBERS_FAILURE';

export const GROUPS_LOAD_REQUEST = 'GROUPS_LOAD_REQUEST';
export const GROUPS_LOAD_SUCCESS = 'GROUPS_LOAD_SUCCESS';
export const GROUPS_LOAD_FAILURE = 'GROUPS_LOAD_FAILURE';

export const GROUP_ACCESS_JOIN_REQUEST = 'GROUP_ACCESS_JOIN_REQUEST';
export const GROUP_ACCESS_JOIN_SUCCESS = 'GROUP_ACCESS_JOIN_SUCCESS';
export const GROUP_ACCESS_JOIN_FAILURE = 'GROUP_ACCESS_JOIN_FAILURE';

export const GROUP_REJECT_JOIN_REQUEST = 'GROUP_REJECT_JOIN_REQUEST';
export const GROUP_REJECT_JOIN_SUCCESS = 'GROUP_REJECT_JOIN_SUCCESS';
export const GROUP_REJECT_JOIN_FAILURE = 'GROUP_REJECT_JOIN_FAILURE';

export const GROUP_ROLE_INCREASE_REQUEST = 'GROUP_ROLE_INCREASE_REQUEST';
export const GROUP_ROLE_INCREASE_SUCCESS = 'GROUP_ROLE_INCREASE_SUCCESS';
export const GROUP_ROLE_INCREASE_FAILURE = 'GROUP_ROLE_INCREASE_FAILURE';

export const GROUP_ROLE_DECREASE_REQUEST = 'GROUP_ROLE_DECREASE_REQUEST';
export const GROUP_ROLE_DECREASE_SUCCESS = 'GROUP_ROLE_DECREASE_SUCCESS';
export const GROUP_ROLE_DECREASE_FAILURE = 'GROUP_ROLE_DECREASE_FAILURE';

export const DEVICE_ADD_REQUEST = 'DEVICE_ADD_REQUEST';
export const DEVICE_ADD_SUCCESS = 'DEVICE_ADD_SUCCESS';
export const DEVICE_ADD_FAILURE = 'DEVICE_ADD_FAILURE';

export const DEVICE_LIST_REQUEST = 'DEVICE_LIST_REQUEST';
export const DEVICE_LIST_SUCCESS = 'DEVICE_LIST_SUCCESS';
export const DEVICE_LIST_FAILURE = 'DEVICE_LIST_FAILURE';

export const DEVICE_OWNERLIST_REQUEST = 'DEVICE_OWNERLIST_REQUEST';
export const DEVICE_OWNERLIST_SUCCESS = 'DEVICE_OWNERLIST_SUCCESS';
export const DEVICE_OWNERLIST_FAILURE = 'DEVICE_OWNERLIST_FAILURE';

export const DEVICE_EDIT_REQUEST = 'DEVICE_EDIT_REQUEST';
export const DEVICE_EDIT_SUCCESS = 'DEVICE_EDIT_SUCCESS';
export const DEVICE_EDIT_FAILURE = 'DEVICE_EDIT_FAILURE';

export const DEVICE_LOCATION_ADD_REQUEST = 'DEVICE_LOCATION_ADD_REQUEST';
export const DEVICE_LOCATION_ADD_SUCCESS = 'DEVICE_LOCATION_ADD_SUCCESS';
export const DEVICE_LOCATION_ADD_FAILURE = 'DEVICE_LOCATION_ADD_FAILURE';

export const DEVICE_LOCATION_LOAD_REQUEST = 'DEVICE_LOCATION_LOAD_REQUEST';
export const DEVICE_LOCATION_LOAD_SUCCESS = 'DEVICE_LOCATION_LOAD_SUCCESS';
export const DEVICE_LOCATION_LOAD_FAILURE = 'DEVICE_LOCATION_LOAD_FAILURE';

export const NOTICE_ADD_REQUEST = 'NOTICE_ADD_REQUEST';
export const NOTICE_ADD_SUCCESS = 'NOTICE_ADD_SUCCESS';
export const NOTICE_ADD_FAILURE = 'NOTICE_ADD_FAILURE';

export const NOTICE_LOAD_REQUEST = 'NOTICE_LOAD_REQUEST';
export const NOTICE_LOAD_SUCCESS = 'NOTICE_LOAD_SUCCESS';
export const NOTICE_LOAD_FAILURE = 'NOTICE_LOAD_FAILURE';

export const NOTICE_INFO_REQUEST = 'NOTICE_INFO_REQUEST';
export const NOTICE_INFO_SUCCESS = 'NOTICE_INFO_SUCCESS';
export const NOTICE_INFO_FAILURE = 'NOTICE_INFO_FAILURE';

export const NOTICE_EDIT_REQEUST = 'NOTICE_EDIT_REQUEST';
export const NOTICE_EDIT_SUCCESS = 'NOTICE_EDIT_SUCCESS';
export const NOTICE_EDIT_FAILURE = 'NOTICE_EDIT_FAILURE';

export const NOTICE_RESET_INFO = 'NOTICE_RESET_INFO';

export const REPAIR_ADD_REQUEST = 'REPAIR_ADD_REQUEST';
export const REPAIR_ADD_SUCCESS = 'REPAIR_ADD_SUCCESS';
export const REPAIR_ADD_FAILURE = 'REPIAR_ADD_FAILURE';

export const REPAIR_LOAD_REQUEST = 'REPAIR_LOAD_REQUEST';
export const REPAIR_LOAD_SUCCESS = 'REPAIR_LOAD_SUCCESS';
export const REPAIR_LOAD_FAILURE = 'REPAIR_LOAD_FAILURE';

export const REPAIR_COMPLETE_REQUEST = 'REPAIR_COMPLETE_REQUEST';
export const REPAIR_COMPLETE_SUCCESS = 'REPAIR_COMPLETE_SUCCESS';
export const REPAIR_COMPLETE_FAILURE = 'REPAIR_COMPLETE_FAILURE';